### ISSUE TITLE
[Bug] 点赞后本楼内的回复引用块消失

### ISSUE THREAD

**Issue by w568w** [OpenTreeHole/treehole-frontend-next#10]
**复现步骤**
1. 任找一有引用的楼层（如<https://www.fduhole.com/#/hole/191516>），对其点赞；
2. 第一条引用（标记为「回复 xxxx」的引用块）消失，其他引用块正常。

**预期行为**
所有引用块都应在点赞后正常显示。

**Comment by dest1n1s** [comment]
Closed on #12 .
