### ISSUE TITLE
[Bug] 首层无文字内容的洞无法从主页进入

### ISSUE THREAD

**Issue by Zhuo19** [OpenTreeHole/treehole-frontend-next#19]
如 洞231333（首层只有一张图片），在洞外显示为：
![image](https://user-images.githubusercontent.com/122052755/231756295-3d0e59eb-55a7-4ecf-9546-3e53d4f45fde.png)
进入某洞的方式似乎是点击预览的文字内容，而在首层只有一张图片的情况下似乎不显示任何预览内容，所以无法点击进入查看全洞。

**Comment by dest1n1s** [comment]
Closed by #22 .
