### ISSUE TITLE
[BUG]markdown语法删除线无法显示，修改带有删除线的内容会去掉~~

### ISSUE THREAD

**Issue by ppolariss** [OpenTreeHole/treehole-frontend-next#20]
1. 在外面看不到删除线，点击修改后才可以看到

![7eafd9fd013160b11cf8f827163f5fa](https://github.com/OpenTreeHole/treehole-frontend-next/assets/100940438/c6e8b5e5-5cd7-41e5-b3c7-df87efc0774a)

2. 上图在点击修改后立即发布，新内容会自动去掉~~，下图为修改后的结果
![27525c850d64fbfcb31766cbde7baea](https://github.com/OpenTreeHole/treehole-frontend-next/assets/100940438/a116e065-e709-401a-9e66-c682d61f8e76)

**Comment by dest1n1s** [comment]
Closed by #22 .
