### ISSUE TITLE
[Feature Request] Url Scheme 重定向

### ISSUE THREAD

**Issue by ivanfei-1** [OpenTreeHole/treehole-frontend-next#21]
Url Scheme 可用于分享树洞内容, 以减少截屏的可能. 目前客户端均已支持使用 Url Scheme 跳转和分享, 见 [PR](https://github.com/DanXi-Dev/DanXi/pull/247) 和 [Commit](https://github.com/DanXi-Dev/DanXi-swift/commit/c8edf94723737f78c53519bc9fb51ae6f7a7f154).

但许多浏览器/社交软件不支持 danxi://forum/... 等 Scheme 的识别. 现在的解决办法法是将分享链接写成形如 https://url.fduhole.com/forum/floor/... 并交由网页端重定向至 danxi://forum/floor/... . 跳转可以不加载任何元素或者在静态页面中进行,  以减少后端和渲染压力.
具体形式和关键词可以进一步探讨, 客户端 Url Scheme 设计可见[飞书文档](https://danxi-dev.feishu.cn/docx/W6ISd9swIoGSnOxXaaOcaeBSnIh).

**Comment by ivanfei-1** [comment]
经讨论, 网页端只需提供自己各种页面的路由, 客户端使用与网页端一致的`Universal Link`跳转.

另外还需网页端和网关改为`history_mode`.

**Comment by dest1n1s** [comment]
Closed by #22 .
