### ISSUE TITLE
[Backward Compatibility] 添加忘记密码的重定向

### ISSUE THREAD

**Issue by w568w** [OpenTreeHole/treehole-frontend-next#9]
现在版本的旦夕客户端（<= 1.3.10）将会在用户忘记密码时重定向至 <https://www.fduhole.com/#/forgetpassword>。

目前，这一页面在新版树洞中表现为空白。为了提高向后兼容性，请重定向至 <https://auth.fduhole.com/register?type=forget_password>。

**Comment by dest1n1s** [comment]
Implemented in #11 .
